name: dbt_run_dev_refresh
run-name: dbt_run_dev_refresh

on:
  workflow_dispatch:
    branches:
      - "main"

concurrency:
  group: ${{ github.workflow }}

jobs:
<<<<<<< HEAD
  called_workflow_template:
    uses: FlipsideCrypto/fsc-evm/.github/workflows/dbt_run_template_dev_refresh.yml@pre-release/v4-beta
    secrets: inherit
=======
  run_dbt_jobs_refresh:
    runs-on: ubuntu-latest
    environment:
      name: workflow_prod

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: install dependencies
        run: |
          pip install -r requirements.txt
          dbt deps
      - name: Run Dev Refresh
        run: |
          dbt run-operation fsc_evm.run_sp_create_prod_clone

  notify-failure:
    needs: [run_dbt_jobs_refresh]
    if: failure()
    uses: FlipsideCrypto/fsc-evm/.github/workflows/slack_notify.yml@main
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  run_dbt_jobs_udfs:
    runs-on: ubuntu-latest
    needs: run_dbt_jobs_refresh
    environment:
      name: workflow_dev

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: install dependencies
        run: |
          pip install -r requirements.txt
          dbt deps

      - name: Run Recreate UDFs
        run: |
          dbt run-operation fsc_utils.create_evm_streamline_udfs --vars '{"UPDATE_UDFS_AND_SPS":True}' -t dev
          dbt run -s livequery_models.deploy.core._live --vars '{"UPDATE_UDFS_AND_SPS":True}' -t dev

  notify-failure2:
    needs: [run_dbt_jobs_udfs]
    if: failure()
    uses: FlipsideCrypto/fsc-evm/.github/workflows/slack_notify.yml@main
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
>>>>>>> origin/main
