version: 2 

sources:
  - name: github_actions
    database: "{{ target.database }}"
    schema: github_actions
    tables:
      - name: workflows
  - name: bronze_streamline
    database: streamline
    schema: "{{ target.database }}"
    tables:
      - name: blocks
      - name: transactions
      - name: receipts
      - name: receipts_by_hash
      - name: traces
      - name: confirm_blocks
      - name: decoded_logs
  - name: crosschain_silver
    database: >-
      {{ 'CROSSCHAIN_DEV' if '_DEV' in target.database.upper() else 'CROSSCHAIN' }}
    schema: silver
    tables:
      - name: labels_combined
      - name: complete_provider_asset_metadata
      - name: complete_native_asset_metadata
      - name: complete_native_prices
      - name: complete_provider_prices
      - name: complete_token_asset_metadata
      - name: complete_token_prices
  - name: bronze_api
    database: "{{ target.database }}"
    schema: bronze_api
    tables:
      - name: contract_abis
  - name: crosschain_public
    database: crosschain
    schema: bronze_public
    tables:
      - name: user_abis
  - name: silver
    database: "{{ target.database }}"
    schema: silver
    tables:
      - name: verified_abis
  - name: fsc_evm_bronze
    database: >-
      {{ 'FSC_EVM_DEV' if '_DEV' in target.database.upper() else 'FSC_EVM' }}
    schema: bronze
    tables:
      - name: master_variable_keys
      - name: master_variable_values